### ISSUE TITLE
Italy ?

### ISSUE THREAD

**Issue by rohandoijode** [ranjan-mohanty/vfs-appointment-bot#10]
Can we do this for Italy ?

**Comment by ranjan-mohanty** [comment]
Hey @rohandoijode, Thanks for reaching out. Sorry, I don't think I will be able to add it right now. I'm currently occupied with my work. If you  want to add it, please feel free to do so

**Comment by karim-manaouil** [comment]
Dear author,
Any updates on this one!
It is in high demand.
Appreciate your effort!

**Comment by ranjan-mohanty** [comment]
Added support for Italy
