### ISSUE TITLE
reCaptcha solving

### ISSUE THREAD

**Issue by anovob** [ranjan-mohanty/vfs-appointment-bot#13]
Now Its need reCaptcha solve. How can I solve reCaptcha with 2captcha api?

**Comment by sai-ravi-chandra-nori** [comment]
Hi, 
I'm completely new to this. Could you please elaborate on how to incorporate the reCaptcha solve into the existing code. As the country I'm applying from also need reCaptcha solve.

Thanks a mill,
Sai.

**Comment by yuchenlichuck** [comment]
Me too, what about polish websites

**Comment by noramirkh** [comment]
Hi,
Do you plan to update with reCaptcha solving?

**Comment by ranjan-mohanty** [comment]
We recently updated the package, and it now handles most scenarios, including auto-solving CAPTCHAs(works in Firefox most of the times). I'll close this issue for now. Feel free to reopen it if you encounter the issue again.
