### ISSUE TITLE
Error when running tool

### ISSUE THREAD

**Issue by justsharan** [ranjan-mohanty/vfs-appointment-bot#15]
I get this error when running the bot. Any next steps?

raise ValueError(
ValueError: Timeout value connect was <object object at 0x7f20179fd490>, but it must be an int, float or None.

**Comment by SuX97** [comment]
Are you using Windows? May due to cannot find firefox binary, you can  add a line in `_VfsClient.py`:
```python
 firefox_options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe' 
```

**Comment by justsharan** [comment]
I still get the same error. I'm running it on Debian, and Firefox is installed at `/usr/bin/firefox` (which is the location I put in the variable).

**Comment by arthemis999** [comment]
This solved the issue for me:

```
pip3 uninstall urllib3
pip3 install urllib3==1.26.5
```

**Comment by AbhayKasturia** [comment]
The fix mentioned by arhtemis999 works on Mac as well.
