### ISSUE TITLE
Login Failed Error

### ISSUE THREAD

**Issue by MohammedIT96** [ranjan-mohanty/vfs-appointment-bot#23]
Hello,

i've changed the url in ( vfs_urls.ini ) file to : https://visa.vfsglobal.com/irq/en/deu/login
because i'm from iraq, but it returns to  Login failed. Please verify your username and password by logging in to the browser and try again.

Then I've made the **Headless** option False
So i checked, it's **login successfully** but it will **not** click on Start New Booking, then closes the browser and return Login Failed ..

Any help please ?

**Comment by MohammedIT96** [comment]
I've made the **Headless** option False
So i checked, it's **login successfully** but i will **not** click on Start New Booking, then closes the browser and return Login Failed ..

Any help please ?

**Comment by ranjan-mohanty** [comment]
It's fixed with the new version
