### ISSUE TITLE
vfs-appointment-bot -sc DZ -dc FR ?? can it be modified to check for these countries

### ISSUE THREAD

**Issue by gcomptedz** [ranjan-mohanty/vfs-appointment-bot#45]
C:\Users\LLCOOLR\vfs-appointment-bot\vfs-appointment-bot>vfs-appointment-bot -sc DZ -dc FR
[2024-05-02 17:07:49,962] Country FR is not supported

**Comment by ranjan-mohanty** [comment]
Hi @gcomptedz,

This script currently only supports IN-DE and IQ-DE. I'm encountering rate limits from the VFS portal for AZ-FR when trying to use it. And unfortunately this script won't work with very strict rate limits.

However, feel free to contribute to the script's development to add support for AZ-FR! We welcome any contributions that can expand its functionality.

**Comment by miloud441980** [comment]
Script vfs
