### ISSUE TITLE
OTP after email & password input

### ISSUE THREAD

**Issue by ramakant7153** [ranjan-mohanty/vfs-appointment-bot#51]
Hi Ranjan,

In Italy VFS , it ask for otp when you input email & password for sign in.

**Comment by ranjan-mohanty** [comment]
Can you share the URL you are trying with?

**Comment by ramakant7153** [comment]
Hi,

Please find below the link.

https://visa.vfsglobal.com/ind/en/ita/login

Regards

**Comment by ranjan-mohanty** [comment]
Hi @ramakant7153 

The bot doesn't support IN-IT (India-Italy) VFS. Supported countries can be found [here](https://github.com/ranjan-mohanty/vfs-appointment-bot?tab=readme-ov-file#supported-countries-and-appointment-parameters)

I will update here once we add the support.
