### ISSUE TITLE
Adding support for CV-PT

### ISSUE THREAD

**Issue by B1NT0N** [ranjan-mohanty/vfs-appointment-bot#53]
**Is your feature request related to a problem? Please describe.**
Not related to any issue.

**Describe the solution you'd like**
I would like to have support for CV-PT (Source country - Cape Verde, Destination country - Portugal). [VFS Link](https://visa.vfsglobal.com/cpv/en/prt/login)

**Describe alternatives you've considered**
I did clone the repo to try adding the support myself, but ended up stuck as this project is beyond my current programming skills. I'm open to be helped or be guided along.

**Additional context**
Currently, the bot only shows the Unsupported Country Message
```
[2024-05-14 00:15:08,323] Country PT is not supported
```

**Comment by B1NT0N** [comment]
Found my way. Turns out I was sleepy at the time.

**Comment by ranjan-mohanty** [comment]
Glad to hear! Please feel free to contribute to the project to support more countries.

**Comment by lernik44** [comment]
@B1NT0N how did you solve it?

- I duplicated "vfs_bot_de.py", renamed the copied file to "vfs_bot_lt.py" (to support Lithuania)
- replaced 'de' to 'lt' in all instances
- also added a few lines in vfs_bot_factory.py
    elif country_lower == "LT":
        from .vfs_bot_lt import VfsBotLt
        return VfsBotLt(source_country_code)

But when I run the command I still get the message Country LT is not supported

**Comment by maravilhosinga** [comment]
> Found my way. Turns out I was sleepy at the time.

Hello, i'm still having issues, can you help me please: +33614778601
