### ISSUE TITLE
How to support others centers/countries?

### ISSUE THREAD

**Issue by fcakyon** [ranjan-mohanty/vfs-appointment-bot#58]
Thanks for the excellent project! Can you please indicate which lines need updating to accommodate other countries or appointment centers?

**Comment by ranjan-mohanty** [comment]
If it's a new destination country, create a new class inheriting from the `VfsBot` base class to represent the country's specific implementation. Additionally, add a new mapping to the `vfs_bot_factory.py` to associate the country code with the newly created class.
