### ISSUE TITLE
cmd error

### ISSUE THREAD

**Issue by rumitvarsani** [ranjan-mohanty/vfs-appointment-bot#6]
![Screenshot 2022-09-02 143225](https://user-images.githubusercontent.com/53006025/188105153-b2ab10b2-f4bb-480d-88b8-fec3f49d989e.png)

**Comment by ranjan-mohanty** [comment]
Hi Rumit, Can you please check the logs and share?

**Comment by rumitvarsani** [comment]
can you please provide the anydesk
Please

**Comment by rumitvarsani** [comment]
[app.log](https://github.com/ranjan-mohanty/vfs-appointment-bot/files/9477459/app.log)
[geckodriver.log](https://github.com/ranjan-mohanty/vfs-appointment-bot/files/9477460/geckodriver.log)

**Comment by sharptornadoqsh** [comment]
I have the same error，how to fix it。I use mac to run the code。

**Comment by arthemis999** [comment]
apparently a geckodriver issue:

> 
> Potential hang with moz:debuggerAddress capability set to true:
> 
> After enabling the site-isolation feature in Firefox with geckodriver 0.32.1
> some WebDriver clients like Selenium that use the Chrome DevTools Protocol (CDP)
> by default for logging events could trigger a hang in Firefox's experimental CDP
> implementation. The fix for this problem will be shipped with Firefox 112.
> Until then the following Firefox preferences should be set:
> 
>     
```
fission.bfcacheInParent: false
fission.webContentIsolationStrategy: 0
```

**Comment by sharptornadoqsh** [comment]
您好，您的邮件我已经收到，我会尽快处理

**Comment by sharptornadoqsh** [comment]
您好，您的邮件我已经收到，我会尽快处理
